#!/run/current-system/sw/bin/bash

OBJECT="$1"
OPERATION="$2"

if [[ $OBJECT == "win10" ]]; then
	case "$OPERATION" in
        	"prepare")
                #systemctl --user start inhibit-idle.service
                /etc/vfio-startup 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
                ;;

                "release")
                #systemctl --user stop inhibit-idle.service
                /etc/vfio-teardown 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
                ;;
	esac
fi

